# Generated by Django 5.1.2 on 2024-12-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_offers_button_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
